config/routes.rb
TimelineNoir::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :clue_info
  resources :case_info
  resources :admin

   root 'welcome#index'

      get 'case/:id' => 'welcome#archive', as: :case_show

  match 'cases', to: 'welcome#mainpage', via: [:get, :post], :as=>"case_page"
  match 'cases_page', to: 'welcome#main', via: [:get, :post], :as=>"cases_pages"

  match '/get_case_title/:case_id', to: 'welcome#get_case_title', via: [:get, :post], :as=>"get_case_title"
  match '/get_case_info/:case_id', to: 'welcome#get_case_info', via: [:get, :post], :as=>"get_case_info"
  match '/test_link', to: 'welcome#test_link', via: [:get, :post], :as=>"test_link"
  match '/get_case_description/:case_id', to: 'welcome#get_case_description', via: [:get, :post], :as=>"get_case_description"
  match '/get_suspect_info/:case_id', to: 'welcome#get_suspect_info', via: [:get, :post], :as=>"get_suspect_info"
  match '/get_victim_info/:case_id', to: 'welcome#get_victim_info', via: [:get, :post], :as=>"get_victim_info"
  match '/get_clue_info/:case_id', to: 'welcome#get_clue_info', via: [:get, :post], :as=>"get_clue_info"
  match '/get_clue_crime_info_cord/:case_id', to: 'welcome#get_clue_crime_info_cord', via: [:get, :post], :as=>"get_clue_crime_info_cord"
  match '/get_clue_stmt_info/:case_id', to: 'welcome#get_clue_stmt_info', via: [:get, :post], :as=>"get_clue_stmt_info"
  match '/get_child_cord/:case_id', to: 'welcome#get_child_cord', via: [:get, :post], :as=>"get_child_cord"
  match '/get_children_data/:case_id', to: 'welcome#get_children_data', via: [:get, :post], :as=>"get_children_data"
  match '/get_suspects_name/:case_id', to: 'welcome#get_suspects_name', via: [:get, :post], :as=>"get_suspects_name"
  match '/get_images/:case_id', to: 'welcome#get_images', via: [:get, :post], :as=>"get_images"
  match '/get_suspect_sr/:case_id', to: 'welcome#get_suspect_sr', via: [:get, :post], :as=>"get_suspect_sr"
  match '/get_suspect_bios/:case_id', to: 'welcome#get_suspect_bios', via: [:get, :post], :as=>"get_suspect_bios"
  match '/get_clue_image_comments/:case_id', to: 'welcome#get_clue_image_comments', via: [:get, :post], :as=>"get_clue_image_comments"
  match '/get_clue_image_url/:case_id', to: 'welcome#get_clue_image_url', via: [:get, :post], :as=>"get_clue_image_url"
  match '/save_post', to: 'welcome#save_post', via: [:post], :as=>"save_post"

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @case_id = CaseInfo.find(3)

    @case=CaseInfo.last
    # @suspects_name=[VictimInfo.first.name+ ", Victim"] + @case.suspect_infos.map{|i| "#{i.name}, #{i.relation}"}
    @suspects_name=[@case.victim_infos.first.name+ ", Victim"] + @case.suspect_infos.map { |i| "#{i.name}, #{i.relation}" }
    # @suspects_name=[@case.victim_infos.map{|i| i.name}+ ", Victim"] + @case.suspect_infos.map{|i| "#{i.name}, #{i.relation}"}
    gon.suspects_name = @suspects_name
    # @images = [VictimInfo.first.image.url] + @case.suspect_infos.map{|i| i.image.url}
    @images = [@case.victim_infos.first.image.url] + @case.suspect_infos.map { |i| i.image.url }
    gon.images= @images
    @suspect_bios=[@case.victim_infos.first.info] + @case.suspect_infos.map { |i| i.information }
    gon.sb=@suspect_bios

    @suspect_sr=['']+ @case.suspect_infos.map { |i| i.interrogate }
    gon.sr=@suspect_sr

    @crimescene=CrimeScene.all
    @cord= @case.clue_infos.map { |i| "#{i.cord_x}, #{i.cord_y}, #{i.cord_z}, #{i.cord_w}" }
    gon.cord=@cord

    @statement=@case.clue_infos.map { |i| "#{i.hover}|| #{i.image.url}|| #{i.info}" }
    gon.stmt=@statement

    @childcord=@case.clue_infos.map { |i| i.children.map { |i| "#{i.cord_x}, #{i.cord_y}, #{i.cord_z}, #{i.cord_w}" } }
    gon.childcordinate=@childcord
    @childdata=@case.clue_infos.map { |i| i.children.map { |i| "#{i.hover}|| #{i.image.url}|| #{i.info}" } }
    gon.childrendata=@childdata

    @facebook_id=@case.facebook_id
    gon.faceid=@facebook_id

    #  @clue_info=@case.crime_scenes.map{|i| "#{i.comment}, #{i.image.url}"}
    # gon.clue_data=@clue_info

  end

  def archive
    @case_id = CaseInfo

    @case=CaseInfo.find(params[:id])
    # @suspects_name=[VictimInfo.first.name+ ", Victim"] + @case.suspect_infos.map{|i| "#{i.name}, #{i.relation}"}
    @suspects_name=[@case.victim_infos.first.name+ ", Victim"] + @case.suspect_infos.map { |i| "#{i.name}, #{i.relation}" }
    # @suspects_name=[@case.victim_infos.map{|i| i.name}+ ", Victim"] + @case.suspect_infos.map{|i| "#{i.name}, #{i.relation}"}
    gon.suspects_name = @suspects_name

    # @images = [VictimInfo.first.image.url] + @case.suspect_infos.map{|i| i.image.url}
    @images = [@case.victim_infos.first.image.url] + @case.suspect_infos.map { |i| i.image.url }
    gon.images= @images
    @suspect_bios=[@case.victim_infos.first.info] + @case.suspect_infos.map { |i| i.information }
    gon.sb=@suspect_bios

    @suspect_sr=['']+ @case.suspect_infos.map { |i| i.interrogate }
    gon.sr=@suspect_sr

    @crimescene=CrimeScene.all
    @cord= @case.clue_infos.map { |i| "#{i.cord_x}, #{i.cord_y}, #{i.cord_z}, #{i.cord_w}" }
    gon.cord=@cord

    @statement=@case.clue_infos.map { |i| "#{i.hover}|| #{i.image.url}|| #{i.info}" }
    gon.stmt=@statement

    @childcord=@case.clue_infos.map { |i| i.children.map { |i| "#{i.cord_x}, #{i.cord_y}, #{i.cord_z}, #{i.cord_w}" } }
    gon.childcordinate=@childcord
    @childdata=@case.clue_infos.map { |i| i.children.map { |i| "#{i.hover}|| #{i.image.url}|| #{i.info}" } }
    gon.childrendata=@childdata

    @facebook_id=@case.facebook_id
    gon.faceid=@facebook_id

    @crime_scene = @case.crime_scenes.first
    # @crime_info=@case.crime_scenes.map{|i| "#{i.comment}, #{i.image.url}"}
    # gon.clue_data=@crime_info
    # render :json => @crime_info
    #     return
    # render :json => @case_id
    # return
    # render :json => gon.images
    # return

  end

  def mainpage
    # @elements = params[:id]
    # @case=CaseInfo.find(params[:id])
    @case_info=CaseInfo.all
    gon.json={
        :timeline=>
            {
                :headline=>"",
                :type=>"default",
                :text=>"The Sachin Memory Project",
                :score=>"",
                :date=>
                    @case_info.map do |i|
                      {
                          :startDate=>i.date.strftime("%Y,%m,%d"),
                          :headline=>i.name,
                          :text=>i.description,
                          :asset=>
                              {
                                  :media=>i.media,
                                  :caption=>""
                              }
                      }
                    end
            }
    }.to_json

    # render :json => gon.json
    #      return
    #render :layout => false
  end


  def main
    render :layout => false
    @case_info=CaseInfo.all
  end





  def test_link
    respond_to do |format|
      format.js do
        @case = CaseInfo.find(3)
        render :json => @case, :callback => params[:callback]
      end
    end
  end

  def get_case_title
    # @case = CaseInfo.find(3)
    # render :json => @case.name,:callback => params[:callback]
    # return
    respond_to do |format|
      format.js do
        @case = CaseInfo.find(3)
        render :json => @case, :callback => params[:callback]
      end
    end
  end

  def get_case_info         # for Case Name  in id caseName row line no 22
    respond_to do |format|
      format.js do
        @case = CaseInfo.find(params[:case_id][0])
        render :json => @case, :callback => params[:callback]
      end
    end
  end

  def get_case_description    # for Case Description in id=briefing line no 27
    respond_to do |format|
      format.js do
      @case = CaseInfo.find(params[:case_id][0])
    render :json => @case.description, :callback => params[:callback]
      end
    end
    # return
  end


  def get_suspect_info
    respond_to do |format|
      format.js do
        @case_suspect_info = CaseInfo.find(params[:case_id][0]).suspect_infos
        # @suspect_array = Array.new()
        # @case.suspect_infos.each do |suspect|
        #   @suspect_array << "#{suspect.name}||#{suspect.relation}||#{suspect.interrogate}||#{suspect.information}||#{suspect.image.url}"
        # end
        render :json=>@case_suspect_info, :callback => params[:callback]
        # return
        # render :json=>@case, :callback => params[:callback]
      end
    end
  end
  def get_clue_info
    respond_to do |format|
      format.js do
        @clue_data = CaseInfo.find(params[:case_id][0]).crime_scenes
        render :json=>@clue_data, :callback => params[:callback]
    # return
      end
    end
  end

  def get_clue_crime_info_cord  # for variable lvl1Nodes
    # respond_to do |format|
    #   format.js do
        @case = CaseInfo.find(params[:case_id][0])
        @crimescene=CrimeScene.all
        @cord= @case.clue_infos.map { |i| "#{i.cord_x}, #{i.cord_y}, #{i.cord_z}, #{i.cord_w}" }
        render :json=>@cord, :callback => params[:callback]
        return
    #   end
    # end
  end

  def get_clue_stmt_info   # for variable lvl1Data
    respond_to do |format|
      format.js do
        @case = CaseInfo.find(params[:case_id][0])
        @statement=@case.clue_infos.map { |i| "#{i.hover}|| #{"http://192.168.2.37:3000"+i.image.url}|| #{i.info}" }
        @cord= @case.clue_infos.map { |i| "#{i.cord_x}, #{i.cord_y}, #{i.cord_z}, #{i.cord_w}" }
        @crime_scene = @case.crime_scenes.first
        @url=@crime_scene.image.url
        @crime_scene = @case.crime_scenes.first
        @comments=@crime_scene.comments
        @comb = @statement, @url, @cord, @comments
        render :json=>@comb, :callback => params[:callback]
        # return
      end
    end
end
  def get_child_cord       # for variable lvl2Nodes
    respond_to do |format|
      format.js do
        @case = CaseInfo.find(params[:case_id][0])
        @childcord=@case.clue_infos.map { |i| i.children.map { |i| "#{i.cord_x}, #{i.cord_y}, #{i.cord_z}, #{i.cord_w}" } }
        render :json=>@childcord, :callback => params[:callback]
        # return
         # return
      end
      end
  end
  def get_children_data    # for variable lvl2Data
    respond_to do |format|
      format.js do
        @case = CaseInfo.find(params[:case_id][0])
        @child_data=@case.clue_infos.map { |i| i.children.map { |i| "#{i.hover}|| #{"http://192.168.2.37:3000"+i.image.url}|| #{i.info}" } }
        render :json=>@child_data, :callback => params[:callback]
        # return
        # return
      end
    end
  end

  def get_suspects_name    # for variable suspectNames
    respond_to do |format|
      format.js do
        @case = CaseInfo.find(params[:case_id][0])
        @suspects_name=[@case.victim_infos.first.name+ ", Victim"] + @case.suspect_infos.map { |i| "#{i.name}, #{i.relation}" }
        render :json=>@suspects_name, :callback => params[:callback]
        # return
        # return
      end
    end
  end
  def get_images           # for variable suspectPhotos
    # respond_to do |format|
    #   format.js do
        @case = CaseInfo.find(params[:case_id][0])
        @images = [@case.victim_infos.first.image.url] + @case.suspect_infos.map { |i| i.image.url }
        render :json=>@images, :callback => params[:callback]
        # return
        # return
    #   end
    # end
  end
  def get_suspect_bios     # for variable suspectBios
    # respond_to do |format|
    #   format.js do
    @case = CaseInfo.find(params[:case_id][0])
    @suspect_bios=[@case.victim_infos.first.info] + @case.suspect_infos.map { |i| i.information }
    render :json=>@suspect_bios, :callback => params[:callback]
    return
    # return
    #   end
    # end
  end
  def get_suspect_sr       # for variable suspectReactions
    respond_to do |format|
      format.js do
    @case = CaseInfo.find(params[:case_id][0])
    @suspect_sr=['']+ @case.suspect_infos.map { |i| i.interrogate }
    render :json=>@suspect_sr, :callback => params[:callback]
    # return
    # return
      end
    end
  end

  def get_clue_image_comments       # in place of  <div class="col-lg-5 crimeSceneOverlay lvl1">
    respond_to do |format|
      format.js do
        @case = CaseInfo.find(params[:case_id][0])
        @crime_scene = @case.crime_scenes.first

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/main.html.erb
<style type="text/css">
    /*table.gridtable {*/
    /*font-family: verdana, arial, sans-serif;*/
    /*font-size: 11px;*/
    /*color: black;*/
    /*border-width: 1px;*/
    /*border-color: white;*/
    /*border-collapse: collapse;*/
    /*}*/

    /*table.gridtable th {*/
    /*border-width: 1px;*/
    /*padding: 8px;*/
    /*border-style: solid;*/
    /*border-color: white;*/
    /*background-color: #dedede;*/
    /*}*/

    /*table.gridtable td {*/
    /*border-width: 1px;*/
    /*padding: 8px;*/
    /*border-style: solid;*/
    /*border-color: white;*/
    /*background-color: #ffffff;*/
    /*}*/
    body {
        background: url("/assets/background.jpg") no-repeat scroll 0 0 / 100% 100% #232323;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-size: 14px;
        margin: 0;
        padding: 0;
        height: 100%;
    }

    .parentalign {
        /*border: 1px dashed white;*/
        height: 220px;
        margin: auto;
        position: relative;
        top: 30%;
        width: 70%;
        left: 10%;
    }

    a {
        text-decoration: none;
        width: 32%;
        margin: 2%;

        height: 40px;
        float: left;
        border: 2px solid white;
        border-radius: 10px;
        color: white;
        text-align: center;
        padding-top: 25px;
        font-size: 18px;
        outline-style: none;
    }

    a:hover {
        text-decoration: none;
        box-shadow: 0 0 37px 4px white, 0 0 36px 4px white inset;
        color: #f4c220;
    }

    #logo {
        width: 50%;
        background: black;
        position: relative;
        top:50%;
        opacity: 0.8;
        padding-left: 20px;
        padding-right: 60px;
        padding-top: 10px;
        padding-bottom: 10px;
        border-bottom-left-radius: 100px;
        border-bottom-right-radius: 200px;
        border-top-left-radius: 100px;
        box-shadow: white 0px 0px 30px;
    }

</style>

<%= link_to image_tag("logo.png", :id=>"logo"), cases_pages_path, :style => "margin:0px; padding:0px;" %>
<div class="parentalign">
  <%= link_to 'This week case', :class=> 'butn' %>
  <%= link_to 'Old cases', case_page_path, :class=> 'butn' %>

</div>
</table>

app/views/welcome/mainpage.html.erb
<style type="text/css">
    html, body {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-size: 14px;
        height: 100%;
        padding: 0px;
        margin: 0px;
    }

    .vco-timeline .vco-navigation .timenav-background {
        background-color: black !important;

    }

    .content-container .layout-text-media .pad-left {
        background-color: #ffffff;
    }

    .slider-item {
        background-color: rgba(0, 0, 0, 0.8) !important;
        width: 50% !important;
        height: 50% !important;
        position: fixed;
        margin-top: 10% !important;
        margin-left: 15% !important;
    }

    .vco-slider .slider-container-mask {
        background: url("/assets/background.jpg") no-repeat black;
        background-size: 100% 100%;
    }

    .vco-slider .nav-previous .nav-container, .vco-slider .nav-next .nav-container {
        color: #ffffff !important;
    }

    .vco-slider .nav-previous .icon {
        background-position: -209px 0 !important;
    }

    .vco-slider .nav-next .icon {
        background-position: -231px 0 !important;
    }

    .vco-storyjs p {
        overflow-y: auto !important;
        margin: 3% !important;
    }

    .media {
        margin: 3% !important;
    }

    .container .date {
        text-align: center;
        font-weight: bold !important;
    }

    #timeline-embed {
        border: 2px dashed black;
    }
</style>

<div id="timeline-embed"></div>

<script type="text/javascript">
    var timeline_config = {
        width: "100%",
        height: "100%",
        debug: true,
        source: JSON.parse(gon.json)
    }
</script>
<script type="text/javascript" src="/assets/storyjs-embed.js"></script>